# Generated by Django 4.0.6 on 2022-07-14 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugares', '0001_initial'),
        ('especies', '0004_categoriastaxonomicas_delete_categorias_taxonomicas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avistamientos',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='idCategoria')),
                ('latitud', models.CharField(max_length=20, null=True, verbose_name='Latitud')),
                ('longitud', models.CharField(max_length=20, null=True, verbose_name='Longitud')),
                ('autor', models.CharField(max_length=20, null=True, verbose_name='Autor')),
                ('notas', models.CharField(max_length=20, null=True, verbose_name='Notas')),
                ('especie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='especies.especie', verbose_name='Especie')),
                ('lugar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lugares.lugares', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'avistamiento',
                'verbose_name_plural': 'avistamientos',
            },
        ),
    ]
