# Generated by Django 4.0.6 on 2022-07-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avistamientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avistamientos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='idCategoria'),
        ),
    ]
