# Generated by Django 4.0.6 on 2022-07-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='idEspecie')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Especiedrgdg',
                'verbose_name_plural': 'Especiesddgdg',
            },
        ),
    ]
