# Generated by Django 4.0.6 on 2022-07-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especie',
            options={'verbose_name': 'Especie', 'verbose_name_plural': 'Especies'},
        ),
        migrations.RemoveField(
            model_name='especie',
            name='nombre',
        ),
        migrations.AddField(
            model_name='especie',
            name='categoria',
            field=models.CharField(blank=True, choices=[('0', 'Reino'), ('1', 'Filo'), ('2', 'Clase'), ('3', 'Orden'), ('4', 'Familia'), ('5', 'Genero'), ('6', 'Especie')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='nombre_cientifico',
            field=models.CharField(max_length=20, null=True, verbose_name='Nombre_Cientifico'),
        ),
        migrations.AddField(
            model_name='especie',
            name='nombre_comun',
            field=models.CharField(max_length=20, null=True, verbose_name='Nombre_Comun'),
        ),
    ]
