# Generated by Django 4.0.6 on 2022-07-14 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0003_remove_especie_categoria_categorias_taxonomicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasTaxonomicas',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='idCategoria')),
                ('reino', models.CharField(max_length=20, null=True, verbose_name='Reino')),
                ('filo', models.CharField(max_length=20, null=True, verbose_name='Filo')),
                ('clase', models.CharField(max_length=20, null=True, verbose_name='Clase')),
                ('orden', models.CharField(max_length=20, null=True, verbose_name='Orden')),
                ('familia', models.CharField(max_length=20, null=True, verbose_name='Familia')),
                ('genero', models.CharField(max_length=20, null=True, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Categoria_Taxonomica',
                'verbose_name_plural': 'Categorias_Taxonomicas',
            },
        ),
        migrations.DeleteModel(
            name='Categorias_taxonomicas',
        ),
        migrations.AddField(
            model_name='especie',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='especies.categoriastaxonomicas', verbose_name='Categoria_Taxonomica'),
        ),
    ]
