# Generated by Django 4.0.6 on 2022-07-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0004_categoriastaxonomicas_delete_categorias_taxonomicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriastaxonomicas',
            name='id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='idCategoria'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='idEspecie'),
        ),
    ]
