# Generated by Django 4.0.6 on 2022-07-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0010_alter_categoriastaxonomicas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriastaxonomicas',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='idCategoria'),
        ),
    ]
