# Generated by Django 4.0.6 on 2022-08-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugares',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='idCategoria'),
        ),
    ]
